In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

data=pd.read_csv('LOG_titanic_x_y_train.csv',delimiter=',')


In [5]:
data.head(5)

Pclass                                            Name     Sex   Age  \
0       2   Weisz, Mrs. Leopold (Mathilde Francoise Pede)  female  29.0   
1       3               Williams, Mr. Howard Hugh "Harry"    male   NaN   
2       2  Morley, Mr. Henry Samuel ("Mr Henry Marshall")    male  39.0   
3       3     Palsson, Mrs. Nils (Alma Cornelia Berglund)  female  29.0   
4       3                          Sutehall, Mr. Henry Jr    male  25.0   

   SibSp  Parch           Ticket    Fare Cabin Embarked  Survived  
0      1      0           228414  26.000   NaN        S         1  
1      0      0         A/5 2466   8.050   NaN        S         0  
2      0      0           250655  26.000   NaN        S         0  
3      0      4           349909  21.075   NaN        S         0  
4      0      0  SOTON/OQ 392076   7.050   NaN        S         0

In [6]:
data.Age.fillna(data.Age.mean(),inplace=True)
new_data=pd.get_dummies(data,columns=['Sex','Embarked','Pclass'])
new_data=new_data.drop(['Name','Ticket','Cabin'], axis=1)
new_data['survived']=new_data['Survived']
del new_data['Survived']
z=np.array(new_data)
x_train=z[:,:-1]
y_train=z[:,-1]
b=pd.read_csv('LOG_titanic_x_test.csv',delimiter=',')
b.Age.fillna(b.Age.mean(),inplace=True)
new_x=pd.get_dummies(b,columns=['Sex','Embarked','Pclass'])
new_x=new_x.drop(['Name','Ticket','Cabin'], axis=1)
x_test=np.array(new_x)

from sklearn.linear_model import LogisticRegression

clf=LogisticRegression(C=0.06)
clf.fit(x_train,y_train)
y_pred=clf.predict(x_test) 
y=np.array(y_pred)
#y_test_pred=np.around(y,decimals=5)
np.savetxt("LOG_titanic_pred.csv",y_pred)
y_pred
#plt.scatter(y_pred,y_train.reshape(-1,1))
#plt.show


G:\ANACONDA3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


array([0., 1., 0., 1., 0., 0., 0., 0., 1., 0., 1., 0., 1., 1., 0., 0., 0.,
       0., 0., 1., 1., 0., 1., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0.,
       0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 1., 1., 0., 1., 0., 0., 0.,
       1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 0.,
       1., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 1., 0., 0., 0.,
       1., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0.,
       1., 0., 1., 1., 0., 0., 0., 0., 0., 1., 1., 0., 1., 0., 0., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0.,
       0., 1., 0., 0., 1., 0., 0., 0., 1., 1., 1., 1., 0., 0., 0., 1., 1.,
       1., 1., 1., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 1., 1., 0., 1.,
       0., 1., 0., 0., 0., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0., 0.,
       0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 1., 1., 0., 0., 0., 0., 1.,
       0., 0.])

In [7]:
clf.score(x_test,y_pred)

1.0

In [8]:
import numpy as np
import pandas as pd

data=pd.read_csv('LOG_titanic_x_y_train.csv',delimiter=',')
data.Age.fillna(data.Age.mean(),inplace=True)
new_data=pd.get_dummies(data,columns=['Sex','Embarked','Pclass'])
new_data=new_data.drop(['Name','Ticket','Cabin'], axis=1)
new_data['survived']=new_data['Survived']
del new_data['Survived']
z=np.array(new_data)
x_train=z[:,:-1]
y_train=z[:,-1]
b=pd.read_csv('LOG_titanic_x_test.csv',delimiter=',')
b.Age.fillna(b.Age.mean(),inplace=True)
new_x=pd.get_dummies(b,columns=['Sex','Embarked','Pclass'])
new_x=new_x.drop(['Name','Ticket','Cabin'], axis=1)
x_t=np.array(new_x)
from sklearn import preprocessing
x_train=preprocessing.Normalizer().fit(z[:,:-1]).transform(z[:,:-1])
y_t=preprocessing.Normalizer().fit(z[:,-1].reshape(-1,1)).transform(z[:,-1].reshape(-1,1))
y_train=y_t.reshape(-1)
#print(y_train.shape)
x_test=preprocessing.Normalizer().fit(x_t).transform(x_t)
from sklearn.linear_model import LogisticRegression

clf=LogisticRegression(C=0.5)
clf.fit(x_train,y_train)
y1_pred=clf.predict(x_test) 
y=np.array(y1_pred)
#y_test_pred=np.around(y,decimals=5)
np.savetxt("LOG_titanic_pred.csv",y1_pred)
y1_pred


G:\ANACONDA3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0.,
       1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 1., 0., 0., 1., 0., 0.,
       0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
       0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1.,
       1., 1., 0., 0., 1., 0., 0., 1., 1., 1., 1., 0., 0., 1., 0., 0., 0.,
       1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0.,
       1., 1., 1., 1., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 1., 1., 0., 1., 1., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 1., 0., 1.,
       0., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 1., 0., 0., 0.,
       0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       1., 1., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0.,
       0., 0., 1., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       0., 0.])

223

In [9]:
df=pd.read_csv(r'C:\Users\PRIYANSHU PANDEY\Downloads\titanic_train.csv')
data.Age.fillna(data.Age.mean(),inplace=True)
new_data=pd.get_dummies(data,columns=['Sex','Embarked','Pclass'])
new_data=new_data.drop(['Name','Ticket','Cabin'], axis=1)
new_data['survived']=new_data['Survived']
del new_data['Survived']
z=np.array(new_data)
x1_train=z[:,:-1]
y1_train=z[:,-1]


In [10]:
x1_train

array([[29.       ,  1.       ,  0.       , ...,  0.       ,  1.       ,
         0.       ],
       [29.7005597,  0.       ,  0.       , ...,  0.       ,  0.       ,
         1.       ],
       [39.       ,  0.       ,  0.       , ...,  0.       ,  1.       ,
         0.       ],
       ...,
       [32.       ,  0.       ,  0.       , ...,  0.       ,  0.       ,
         1.       ],
       [22.       ,  0.       ,  0.       , ...,  0.       ,  0.       ,
         1.       ],
       [29.7005597,  1.       ,  0.       , ...,  0.       ,  0.       ,
         1.       ]])

In [33]:
clf2=LogisticRegression(C=1)
clf2.fit(x1_train,y1_train)

LogisticRegression(C=1, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [38]:
ypd = clf.predict(x_test)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0.])