In [30]:
import numpy as np

#print(np.arange(10))

a = np.array([0, 1, 2, 3])
#print(a.shape)                #to get the size of the array

#l=[int(x) for x in input().strip().split(" ")]
#print(np.array(l))

a=np.zeros(10,int)          #zeros is a function to get all zeros, and we can change the data type
#print(a)
a.dtype                     #to get the data type of numpy array

c=np.zeros((2,3,4), int)           #multi-dimensional array

c[0]='1'                      #to insert a elemnt to whole column and row      #(d[0:1,:])
#print(b)                                                                      #d[1:3,2:3])
                                                                               #d[2:3,0:2]) rev
                                                                               #d[1:2,0:2]) rev
c[0][2]='2'                     #to insert a elemnt to whole column 
#print(b)

c[0][2][3]='3'                  #to insert a elemnt to a particular place
#print(c)

d=np.array([[1,2,3],[4,5,6],[7,8,9]])    #slicing
print(d[1:2,0:2])

[[4 5]]


In [18]:
import math as m
m.sqrt(10)


3.1622776601683795

In [31]:
# numpy operations
a=np.array([1,2,3])
b=np.array([4,5,6])

print(a+b)
print(a-b)
print(a*b)
print(a**b)
print(a+2)
print(2+b)
print(a-2)
print(a*2)
 
    

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[  1  32 729]
[3 4 5]
[6 7 8]
[-1  0  1]
[2 4 6]


In [44]:
# functions of math operations

a=np.array([5,1,2,1])
a.mean()
#a.sum()

2.25

In [37]:
a=np.array([1,2,3])
b=np.array([4,5,6])
d=((a-b)**2).sum()
m.sqrt(d)

c=((a-a.mean())**2).sum()
print(c)

2.0


In [36]:
a=np.array([0,1,2,3])
b=np.array([2,3,4,5])
a+a
for i in range(2,1,-1):
    print(a[i])
# a.mat() also exist and they are strictly 2-d arrays

2


In [ ]:
np.array(int(x) for x in input().strip().split(" "))

In [ ]:
# to print spiral of arrays

import numpy as np
l=[int(i) for i in input().strip().split(" ")]
n=l[0]
m=l[1]
l.pop(0)
l.pop(0)
x=np.array(l)
x=x.reshape(n,m)
k,l=0,0
while(k<=n and l<=m):
    if (l<m and k<n):
        for i in range(l,m):
            print(x[k][i],end=' ')
    k=k+1
    if (l<m and k<n):
        for i in range(k,n):
            print(x[i][m-1],end=' ')
    m=m-1
    if (l<m and k<n):
        for i in range(m,l,-1):
            print(x[n-1][i-1],end=' ')
    n=n-1
    if(l<m and k<n):
        for i in range(n,k,-1):
            print(x[i-1][l],end=' ')
    l=l+1  

In [4]:
#to get equilibrium index in an array

x`
x=np.array(l)
sum=x.sum()
lsum=0
for i in range(n):
    sum=sum-x[i]
    if(sum==lsum):
        print(i)
        break
    lsum=lsum+x[i]

7
-7 1 5 2 -4 3 0
3


In [3]:
str=(input())

print(str(0])

EWF


TypeError: 'str' object is not callable