<img src='https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/NumPy_logo.svg/1200px-NumPy_logo.svg.png' height='1000' width='500'>

In [5]:
import numpy as np
import time
import sys

a = range(100)
print(sys.getsizeof(10)*len(a))

b = np.arange(100)
print(b.size*b.itemsize)

2800
400


In [7]:
import numpy as np
import time
import sys

size = 1000000

A1 = range(size)
A2 = range(size)

B1 = np.arange(size)
B2 = np.arange(size)

#For list
start = time.time()
result = [(x,y) for x,y in zip(A1,A2)]
print((time.time()-start)*1000)

#For NumPy Arrays
start = time.time()
result = B1 + B2
print((time.time()-start)*1000)

294.7399616241455
99.93386268615723


## 1. Array Attributes

In [4]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
print(a.shape)

(2, 3)


In [6]:
#this resizes the ndarray
a = np.array([[1,2,3],[4,5,6]])
a.shape = (3,2)
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [9]:
a = np.array([[1,2,3],[4,5,6]])
b = a.reshape(3,2)
print(b)

[[1 2]
 [3 4]
 [5 6]]


In [11]:
#an array of evenly spaced numbers
import numpy as np
a = np.arange(24)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [16]:
#this is one dimensional array
import numpy as np
a = np.arange(24)
print(a.ndim)

#now reshape it
b = a.reshape(2,4,3)
print(b.ndim) #b is having three dimensions

1
3


In [18]:
#dtypeof array is int8 (1 byte)
import numpy as np
x = np.array([1,2,3,4,5], dtype=np.int8)
print(x.itemsize)

1


In [19]:
#dtype of array is now float32 (4 bytes)
import numpy as np
x = np.array([1,2,3,4,5], dtype=np.float32)
print(x.itemsize)

4


## 2. Indexing  & Slicing

## 3. Iterating over array

## 4. Array manipulation

## 5. Binary operators

## 6. Statistical Functions

## 7. Sorting & Searching 

## 8. Counting funtions