<img src='https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/NumPy_logo.svg/1200px-NumPy_logo.svg.png' height='1000' width='500'>

In [5]:
import numpy as np
import time
import sys

a = range(100)
print(sys.getsizeof(10)*len(a))

b = np.arange(100)
print(b.size*b.itemsize)

2800
400


In [7]:
import numpy as np
import time
import sys

size = 1000000

A1 = range(size)
A2 = range(size)

B1 = np.arange(size)
B2 = np.arange(size)

#For list
start = time.time()
result = [(x,y) for x,y in zip(A1,A2)]
print((time.time()-start)*1000)

#For NumPy Arrays
start = time.time()
result = B1 + B2
print((time.time()-start)*1000)

294.7399616241455
99.93386268615723


## 1. Array Attributes

In [4]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
print(a.shape)

(2, 3)


In [6]:
#this resizes the ndarray
a = np.array([[1,2,3],[4,5,6]])
a.shape = (3,2)
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [9]:
a = np.array([[1,2,3],[4,5,6]])
b = a.reshape(3,2)
print(b)

[[1 2]
 [3 4]
 [5 6]]


In [11]:
#an array of evenly spaced numbers
import numpy as np
a = np.arange(24)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [16]:
#this is one dimensional array
import numpy as np
a = np.arange(24)
print(a.ndim)

#now reshape it
b = a.reshape(2,4,3)
print(b.ndim) #b is having three dimensions

1
3


In [18]:
#dtypeof array is int8 (1 byte)
import numpy as np
x = np.array([1,2,3,4,5], dtype=np.int8)
print(x.itemsize)

1


In [19]:
#dtype of array is now float32 (4 bytes)
import numpy as np
x = np.array([1,2,3,4,5], dtype=np.float32)
print(x.itemsize)

4


## 2. Indexing  & Slicing

In [21]:
import numpy as np 
a = np.arange(10) 
s = slice(2,7,2) 
print(a[s])

[2 4 6]


In [24]:
import numpy as np 
a = np.arange(10) 
b = a[2:7:2] 
print(b)

[2 4 6]


In [28]:
# slice items starting from index 
import numpy as np 
a = np.arange(10) 
print(a[5:])

[5 6 7 8 9]


In [30]:
# slice items between indexes 
import numpy as np 
a = np.arange(10) 
print(a[2:5])

[2 3 4]


## 3. Iterating over array

In [35]:
import numpy as np
a = np.arange(0,60,5)
a = a.reshape(3,4)

print('Original array is:')
print(a)
print('\n')

print('Modified array is:')
for x in np.nditer(a):
    print(x,end=' ')

Original array is:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


Modified array is:
0 5 10 15 20 25 30 35 40 45 50 55 

In [36]:
import numpy as np
a = np.arange(0,60,5)
a = a.reshape(3,4)
print('Original array is:')
print(a)
print('\n')

for x in np.nditer(a, op_flags = ['readwrite']):
    x[...] = 2*x
print('Modified array is:')
print(a)

Original array is:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


Modified array is:
[[  0  10  20  30]
 [ 40  50  60  70]
 [ 80  90 100 110]]


## 4. Array manipulation

In [42]:
import numpy as np 
a = np.arange(8).reshape(2,4) 

print('The original array is:') 
print(a) 
print('\n')  

print('After applying ravel function:') 
print(a.ravel()) 
print('\n')

print('The flattened array is:') 
print(a.flatten()) 

The original array is:
[[0 1 2 3]
 [4 5 6 7]]


After applying ravel function:
[0 1 2 3 4 5 6 7]


The flattened array is:
[0 1 2 3 4 5 6 7]


In [47]:
import numpy as np 
a = np.arange(12).reshape(3,4) 

print('The original array is:') 
print(a)  
print('\n') 

print('The transposed array is:') 
print(np.transpose(a))
print('\n')

print('Array after applying the function:') 
print(a.T)

The original array is:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


The transposed array is:
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


Array after applying the function:
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [51]:
import numpy as np 
a = np.array([[1,2],[3,4]]) 

print('First array:') 
print(a) 
print('\n')  
b = np.array([[5,6],[7,8]]) 

print('Second array:') 
print(b) 
print('\n')  
# both the arrays are of same dimensions 

print('Joining the two arrays along axis 0:') 
print(np.concatenate((a,b))) 
print('\n')

print('Stack the two arrays along axis 0:') 
print(np.stack((a,b),0)) 

First array:
[[1 2]
 [3 4]]


Second array:
[[5 6]
 [7 8]]


Joining the two arrays along axis 0:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


Stack the two arrays along axis 0:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [75]:
import numpy as np 
a = np.array([[1,2,3],[4,5,6]]) 

print('First array:') 
print(a) 
print('\n')  

print('Append elements to array:') 
print(np.append(a, [7,8,9])) 
print('\n') 

print('Insert elements to array:') 
print(np.insert(a,6,[7,8,9]))
print('\n')

print('Delete an elements in array:') 
print(np.delete(a,5))

First array:
[[1 2 3]
 [4 5 6]]


Append elements to array:
[1 2 3 4 5 6 7 8 9]


Insert elements to array:
[1 2 3 4 5 6 7 8 9]


Delete an elements in array:
[1 2 3 4 5]


## 5. Binary operators

In [77]:
import numpy as np 
print('Binary equivalents of 13 and 17:')  
a,b = 13,17 
print(bin(a), bin(b)) 
print('\n')  

print('Bitwise AND of 13 and 17:')  
print(np.bitwise_and(13, 17))
print('\n')

print('Bitwise OR of 13 and 17:')  
print(np.bitwise_or(13, 17))
print('\n')


print('Invert of 13 where dtype of ndarray is uint8:') 
print(np.invert(np.array([13], dtype = np.uint8)))

Binary equivalents of 13 and 17:
0b1101 0b10001


Bitwise AND of 13 and 17:
1


Bitwise OR of 13 and 17:
29


Invert of 13 where dtype of ndarray is uint8:
[242]


## 6. Statistical Functions

## 7. Sorting & Searching 

## 8. Counting funtions